services:
  partservice:
    image: dweucloudadpacr.azurecr.io/bmw.cloudadoption.part-c:${TAG}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9001:80"
    depends_on:
      - kafka
      - sql

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    restart: unless-stopped
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:3.0.1'
    restart: unless-stopped
    ports:
      - '9094:9094'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CLIENT:PLAINTEXT,EXTERNALCLIENT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:9093,CLIENT://:9092,EXTERNALCLIENT://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9093,CLIENT://kafka:9092,EXTERNALCLIENT://localhost:9094
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CLIENT_USERS=user
      - KAFKA_CFG_TLS_CLIENT_AUTH=none
      - KAFKA_CLIENT_PASSWORDS=password
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  akhq:
    image: tchiotludo/akhq:0.21.0
    volumes:
      - ./application.yml:/app/application.yml
    ports:
      - "8070:8080"
    depends_on:
      - kafka

  sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      - "ACCEPT_EULA=Y"
      - "MSSQL_SA_PASSWORD=Passw0rd!1"
      - "MSSQL_PID=Express"
