trigger:
  - main

variables:
  - group: acr-credentials

pool:
  name: self-hosted

steps:
  - task: Bash@3
    displayName: Angular Build
    inputs:
      targetType: 'inline'
      script: |
        npm install
        npm run lint
        npm run test
        ng build
  - task: Docker@2
    displayName: Login to ACR
    inputs:
      command: login
      containerRegistry: dweuttdblueacr.azurecr.io
  - task: Bash@3
    displayName: Docker Build & Push
    inputs:
      targetType: 'inline'
      script: |
        docker build -t dweuttdblueacr.azurecr.io/bmw.cloudadoption.part-web:latest -f Dockerfile .
        docker push dweuttdblueacr.azurecr.io/bmw.cloudadoption.part-web:latest
