name: Build

on:
  push:
    branches:
      - main

  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME : "bmw.cloudadoption.parts-c"
      IMAGE_TAG: latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}

      - name: Login ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_IMAGE_NAME: ${{ env.IMAGE_NAME }}
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_IMAGE_NAME:$IMAGE_TAG -f BMW.CloudAdoption.Parts.Api/Dockerfile .
          docker push $ECR_REGISTRY/$ECR_IMAGE_NAME:$IMAGE_TAG